include: package:very_good_analysis/analysis_options.yaml
  
linter:
 rules:
  flutter_style_todos: false
  one_member_abstracts: false
  public_member_api_docs: false
  
analyzer:
 exclude:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.config.dart"
  - "**/generated/*"
 errors:
  invalid_annotation_target: ignore