name: ok_mobile_app
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  loader_overlay: ^5.0.0
  local_session_timeout: ^3.2.0
  ok_mobile_admin: any
  ok_mobile_auth: any
  ok_mobile_bags: any
  ok_mobile_bluefletch: any
  # ok_mobile_boxes: any TODO: enable boxes when ready
  ok_mobile_common: any
  ok_mobile_counting_center: any
  ok_mobile_data: any
  ok_mobile_domain: any
  ok_mobile_pickups: any
  ok_mobile_returns: any
  ok_mobile_scanner: any
  ok_mobile_translations: any

dev_dependencies:
  build_runner: ^2.4.15
  flutter_flavorizr: ^2.2.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  integration_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic

flavorizr:
  flavors:
    prd:
      app:
        name: "OK Mobile"
      android:
        applicationId: "com.ok.mobile"
        icon: "assets/icons/app_icon.png"
        resValues:
          app_name:
            type: string
            value: "OK Mobile"
          auth_path:
            type: string
            value: "/lvGC0B4SWYU8tNPHg/bdMjQinZQ="
          redirect_host_name:
            type: string
            value: "com.ok.mobile"
        customConfig:
          signingConfig: signingConfigs.release
      ios:
        bundleId: "com.ok.mobile"
        icon: "assets/icons/app_icon.png"

    uat:
      app:
        name: "OK Mobile UAT"
      android:
        applicationId: "com.ok.mobile.uat"
        icon: "assets/icons/app_icon_uat.png"
        resValues:
          app_name:
            type: string
            value: "OK Mobile UAT"
          auth_path:
            type: string
            value: "/lvGC0B4SWYU8tNPHg/bdMjQinZQ="
          redirect_host_name:
            type: string
            value: "com.ok.mobile.uat"
        customConfig:
          signingConfig: signingConfigs.release
      ios:
        bundleId: "com.ok.mobile.uat"
        icon: "assets/icons/app_icon_uat.png"

    tst:
      app:
        name: "OK Mobile Tst"
      android:
        applicationId: "com.ok.mobile.tst"
        icon: "assets/icons/app_icon_tst.png"
        resValues:
          app_name:
            type: string
            value: "OK Mobile Tst"
          auth_path:
            type: string
            value: "/lvGC0B4SWYU8tNPHg/bdMjQinZQ="
          redirect_host_name:
            type: string
            value: "com.ok.mobile.stage"
        customConfig:
          signingConfig: signingConfigs.release
      ios:
        bundleId: "com.ok.mobile.tst"
        icon: "assets/icons/app_icon_tst.png"

    dev:
      app:
        name: "OK Mobile Dev"
      android:
        applicationId: "com.ok.mobile.dev"
        icon: "assets/icons/app_icon_dev.png"
        resValues:
          app_name:
            type: string
            value: "OK Mobile Dev"
          auth_path:
            type: string
            value: "/lvGC0B4SWYU8tNPHg/bdMjQinZQ="
          redirect_host_name:
            type: string
            value: "com.ok.mobile.dev"
      customConfig:
        signingConfig: signingConfigs.release
      ios:
        bundleId: "com.ok.mobile.dev"
        icon: "assets/icons/app_icon_dev.png"

    offline:
      app:
        name: "OK Mobile Offline"
      android:
        applicationId: "com.ok.mobile.offline"
        resValues:
          app_name:
            type: string
            value: "OK Mobile Offline"
          auth_path:
            type: string
            value: "/lvGC0B4SWYU8tNPHg/bdMjQinZQ="
          redirect_host_name:
            type: string
            value: "com.ok.mobile.offline"
      customConfig:
        signingConfig: signingConfigs.debug
      ios:
        bundleId: "com.ok.mobile.offline"
