name: ok_mobile_admin
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.29.0"

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  injectable: ^2.5.0
  ok_mobile_auth: any
  ok_mobile_common: any
  ok_mobile_data: any
  ok_mobile_domain: any
  ok_mobile_returns: any
  ok_mobile_scanner: any
  ok_mobile_translations: any

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  dartz: ^0.10.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
