name: ok_mobile_domain
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.29.0"

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  http: ^1.5.0
  http_certificate_pinning: ^3.0.1
  injectable: ^2.5.0
  jwt_decode: ^0.3.1
  ok_mobile_common: any
  ok_mobile_data: any
  ok_mobile_translations: any
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  shared_preferences: ^2.5.2
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
