name: ok_mobile_common
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.29.0"

dependencies:
  audioplayers: ^6.4.0
  auto_size_text: ^3.0.0
  azure_application_insights: ^5.0.1
  checkdigit: ^0.3.1
  collection: ^1.19.1
  device_info_plus: ^11.3.3
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  external_path: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_slidable: ^4.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  http: ^1.3.0
  injectable: ^2.5.0
  intl: ^0.20.2
  mobile_scanner: 6.0.10
  ok_mobile_admin: any
  ok_mobile_auth: any
  ok_mobile_data: any
  ok_mobile_datawedge_scanner: any
  ok_mobile_domain: any
  ok_mobile_returns: any
  ok_mobile_translations: any
  package_info_plus: ^8.3.0
  permission_handler: ^11.4.0
  root_checker_plus: ^1.0.0
  shared_preferences: ^2.5.2
  table_calendar: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/sounds/

flutter_gen:
  output: lib/generated/flutter_gen
