name: ok_mobile_scanner
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.29.0"

dependencies:
  camera: ^0.11.1
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  mobile_scanner: 6.0.10
  ok_mobile_bags: any
  # ok_mobile_boxes: any// TODO enable boxes when ready
  ok_mobile_common: any
  ok_mobile_counting_center: any
  ok_mobile_data: any
  ok_mobile_datawedge_scanner: any
  ok_mobile_domain: any
  ok_mobile_returns: any
  ok_mobile_translations: any
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
