name: ok_mobile_data
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.29.0"

dependencies:
  collection: ^1.19.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  external_path: ^2.2.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.1.0
  get_it: ^8.0.3
  http: ^1.3.0
  injectable: ^2.5.0
  intl: ^0.20.2
  jwt_decode: ^0.3.1
  ok_mobile_bluefletch: any
  ok_mobile_common: any
  ok_mobile_domain: any
  ok_mobile_imei: any
  ok_mobile_translations: any
  path: ^1.9.1
  permission_handler: ^11.4.0
  pkce: ^1.1.0+1
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9
  sqflite_common_ffi: ^2.3.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
